[project]
name = "patch-jetbrains"
version = "0.1.0"
description = "A utility to patch JetBrains' IDEs with modified classes"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=25.1.0",
    "docopt>=0.6.2",
    "loguru>=0.7.3",
]

[tool.black]
line-length = 79
